version: '3.5'
services:
  db_volume:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql
  app:
    build: 
      context: ./
    links:
      - db_volume
    ports:
      - 443:443
volumes:
  db_volume:
  app:
