"""Unique student name & address.

Revision ID: 57a0f3e9bfae
Revises: fb10ae7d0137
Create Date: 2022-05-24 06:42:15.296323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a0f3e9bfae'
down_revision = 'fb10ae7d0137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('student', 'address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('student', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
