"""initial migration

Revision ID: 7c81f697ad5d
Revises: 
Create Date: 2022-05-15 17:30:39.952594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c81f697ad5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qcm', 'password')
    op.alter_column('teacher', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_unique_constraint(None, 'teacher', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    op.alter_column('teacher', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('qcm', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
