"""Open/close QCM

Revision ID: dc676aa909b9
Revises: d5d7dc6c5cd0
Create Date: 2022-05-28 16:15:51.575362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc676aa909b9'
down_revision = 'd5d7dc6c5cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qcm', sa.Column('is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qcm', 'is_open')
    # ### end Alembic commands ###
