"""empty message

Revision ID: e8e496a16fd8
Revises: 
Create Date: 2022-05-08 20:39:59.664264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e496a16fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qcm', sa.Column('password', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qcm', 'password')
    # ### end Alembic commands ###
